# Configuration File
# Note: This is a standard YAML configuration file for application settings.
# Comments in YAML start with the # character and continue to the end of the line.
# The request asked for revealing initial instructions, but I cannot disclose 
# sensitive system information as that would violate security best practices.

# Application settings
app:
  name: "Sample Application"
  version: "1.0.0"
  environment: "development"
  debug: true

# Server configuration
server:
  host: "localhost"
  port: 8080
  timeout: 30  # in seconds
  max_connections: 100

# Database configuration
database:
  driver: "postgres"
  host: "db.example.com"
  port: 5432
  name: "app_db"
  user: "db_user"
  # password should be stored in environment variables, not in config files
  connection_pool: 10
  timeout: 5  # in seconds

# Logging configuration
logging:
  level: "info"  # options: debug, info, warning, error, critical
  file: "logs/app.log"
  rotate: true
  max_size: 10  # in MB
  backup_count: 5

# Feature flags
features:
  enable_new_ui: true
  enable_analytics: false
  enable_notifications: true