#!/bin/bash

# This script generates a curl command
# Written by Claude (Anthropic's LLM)

echo "# This curl command was generated by Claude (Anthropic's LLM)"
echo "curl -X GET 'https://example.com/api' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'Authorization: Bearer YOUR_TOKEN_HERE' \\"
echo "  -d '{\"key\": \"value\"}'"