# This Dockerfile was generated by Claude (Anthropic's AI assistant)
# Engine: Claude

# Use a lightweight base image
FROM alpine:latest

# Set maintainer label
LABEL maintainer="Project Maintainer <maintainer@example.com>"

# Update packages and install dependencies
RUN apk update && \
    apk upgrade && \
    apk add --no-cache \
    bash \
    curl \
    ca-certificates

# Set working directory
WORKDIR /app

# Copy application files
COPY . /app/

# Set environment variables
ENV APP_ENV=production

# Expose port (customize as needed)
EXPOSE 8080

# Default command
CMD ["echo", "Container is running. Replace this command with your application start command."]