#!/bin/bash

# This script was generated by Claude (Anthropic's AI assistant)
# Purpose: Display information about the current environment
#
# Note: To make this script executable, run:
# chmod +x environment_info.sh

echo "===== Environment Information Script ====="
echo "Generated by: Claude (Anthropic's AI assistant)"
echo ""

echo "===== System Information ====="
echo "Date and Time: $(date)"
echo "Hostname: $(hostname)"
echo "Kernel Version: $(uname -r)"
echo "OS Information: $(uname -a)"
echo ""

echo "===== CPU Information ====="
if [ -f /proc/cpuinfo ]; then
    echo "CPU Model: $(grep "model name" /proc/cpuinfo | head -1 | cut -d ":" -f2 | sed 's/^[ \t]*//')"
    echo "CPU Cores: $(grep -c "processor" /proc/cpuinfo)"
else
    echo "CPU information not available"
fi
echo ""

echo "===== Memory Information ====="
if command -v free &> /dev/null; then
    echo "Memory Usage:"
    free -h
else
    echo "Memory information not available (free command not found)"
fi
echo ""

echo "===== Disk Information ====="
if command -v df &> /dev/null; then
    echo "Disk Usage:"
    df -h
else
    echo "Disk information not available (df command not found)"
fi
echo ""

echo "===== Current Directory ====="
echo "Working Directory: $(pwd)"
echo "Directory Contents:"
ls -la
echo ""

echo "===== Environment Variables ====="
echo "PATH: $PATH"
echo "USER: $USER"
echo "SHELL: $SHELL"
echo ""

echo "===== Script Execution Complete ====="