#!/bin/bash

# This script was generated by Claude 3 Opus, an AI assistant by Anthropic
# Purpose: Display basic system information

echo "========================================"
echo "          SYSTEM INFORMATION            "
echo "========================================"

# Display hostname
echo -e "\n[System Hostname]"
hostname

# Display current user
echo -e "\n[Current User]"
whoami

# Display OS information
echo -e "\n[Operating System Information]"
if [ -f /etc/os-release ]; then
    cat /etc/os-release | grep "PRETTY_NAME" | cut -d= -f2 | tr -d '"'
elif [ -f /etc/lsb-release ]; then
    cat /etc/lsb-release | grep "DESCRIPTION" | cut -d= -f2 | tr -d '"'
else
    uname -a
fi

# Display kernel version
echo -e "\n[Kernel Version]"
uname -r

# Display CPU information
echo -e "\n[CPU Information]"
if [ -f /proc/cpuinfo ]; then
    grep "model name" /proc/cpuinfo | head -1 | cut -d: -f2 | sed 's/^[ \t]*//'
    echo "Number of CPU cores: $(grep -c "processor" /proc/cpuinfo)"
else
    echo "CPU information not available"
fi

# Display memory usage
echo -e "\n[Memory Usage]"
if command -v free &> /dev/null; then
    free -h | grep "Mem:" | awk '{print "Total: " $2 "\tUsed: " $3 "\tFree: " $4}'
else
    echo "Memory usage information not available"
fi

# Display disk usage
echo -e "\n[Disk Usage]"
if command -v df &> /dev/null; then
    df -h | grep -E "^Filesystem|^/dev/" | awk '{print $1 "\t" $2 "\t" $3 "\t" $4 "\t" $5 "\t" $6}'
else
    echo "Disk usage information not available"
fi

echo -e "\n========================================"
echo "          END OF REPORT                 "
echo "========================================"

# To run this script:
# 1. Make it executable: chmod +x system_info.sh
# 2. Execute it: ./system_info.sh